version: '3.1'

services: 
    db:
        image: postgres
        restart: always
        ports:
          - "5432:5432"
        volumes:
          - ./pgdb/:/var/lib/postgresql/data
        env_file: .env


    web:
        build: .
        command:  python3 manage.py runserver 0.0.0.0:8000
        ports: 
            - 8000:8000
        depends_on:
            - "db"
            - "redisdb"
        env_file: .env

    

    celery:
        build: 
            context: .
            dockerfile: celery.dockerfile
        command:  celery -A ecommerce worker --beat --scheduler django --loglevel=info
        depends_on:
            - "db"
            - "redisdb"
        env_file: .env
    
    redisdb:
        image: redis
        restart: always
        ports:
            - 6379:6379