# Generated by Django 3.1 on 2022-05-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='slug_az',
            field=models.SlugField(editable=False, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='productversion',
            name='slug_en',
            field=models.SlugField(editable=False, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='productversion',
            name='title_az',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productversion',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='slug',
            field=models.SlugField(editable=False, max_length=70),
        ),
    ]
