# Generated by Django 3.1 on 2022-05-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220505_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='slug',
            field=models.SlugField(editable=False, max_length=70),
        ),
    ]
