# Generated by Django 4.0.2 on 2022-03-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
    ]
