# Generated by Django 3.2.13 on 2022-06-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productversion_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyname',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propertynames', to='product.category'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='productversion',
            field=models.ManyToManyField(blank=True, related_name='wishproduct', to='product.ProductVersion'),
        ),
    ]
