# Generated by Django 4.0.2 on 2022-03-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_basket_basketitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasketItems',
            new_name='BasketItem',
        ),
    ]
