# Generated by Django 4.0.2 on 2022-03-31 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productversion_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='discount',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productdiscount', to='product.discount'),
        ),
    ]
