# Generated by Django 4.0.2 on 2022-03-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_basketitems_basketitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
