# Generated by Django 3.1 on 2022-05-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220505_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='slug',
            field=models.SlugField(max_length=70),
        ),
    ]
