# Generated by Django 3.2.13 on 2022-06-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220613_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Comment'),
        ),
    ]
