# Generated by Django 3.1 on 2022-05-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220517_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyname',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propertynames', to='product.category'),
        ),
    ]
