# Generated by Django 3.2.13 on 2022-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220705_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversion',
            name='new_price',
        ),
        migrations.AddField(
            model_name='productversion',
            name='discount_price',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='DiscountPrice'),
        ),
    ]
