# Generated by Django 4.0.2 on 2022-05-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='slug', editable=False, max_length=70),
            preserve_default=False,
        ),
    ]
