# Generated by Django 4.0.2 on 2022-05-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220505_1118'),
        ('blog', '0002_blog_slug'),
    ]

    operations = [
    ]
