# Generated by Django 4.0.2 on 2022-05-10 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_merge_0002_auto_20220505_1118_0002_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_az',
            field=models.SlugField(editable=False, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_en',
            field=models.SlugField(editable=False, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_az',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
