# Generated by Django 4.0.2 on 2022-05-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_description_az_blog_description_en_blog_slug_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug_az',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_en',
        ),
    ]
