# Generated by Django 4.0.2 on 2022-03-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_subcategory'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='productVersion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.productversion', verbose_name='Product Version'),
        ),
    ]
