# Generated by Django 3.1 on 2022-03-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(max_length=70, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=70, verbose_name='Last Name')),
                ('companyname', models.CharField(max_length=80, verbose_name='Company Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('town', models.CharField(max_length=70, verbose_name='Town/City')),
                ('country', models.CharField(max_length=70, verbose_name='Country')),
                ('email', models.EmailField(max_length=50, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=40, verbose_name='Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
