# Generated by Django 3.2.13 on 2022-06-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220613_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='sub_total',
        ),
    ]
