# Generated by Django 3.2.13 on 2022-07-05 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_basket_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='size',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Size'),
            preserve_default=False,
        ),
    ]
