# Generated by Django 4.0.2 on 2022-03-11 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0003_alter_basket_author_alter_basketitem_basket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='productVersion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productversion'),
        ),
    ]
