# Generated by Django 3.2.13 on 2022-07-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_basketitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Size'),
        ),
    ]
